---
title: "Variance Waterfall"
output: html_document
---

```{r Organize data for graph, message=FALSE}
library(readxl)
library(tidyverse)
library(ggthemes)
library(wesanderson)
library(grid)
library(gridExtra)
library(gtable)

bluescope_lightblue <- "#49b4e6"
bluescope_darkgray <- "#7191a9"
bluescope_white <- "#feffff"
bluescope_lightgray <- "#ffffff"
waterfall_palette <- c("#49b4e6", "#7191a9", "#be5019")
title_text <- 20
subtitle_text <- 16
current_month <- "Oct"
current_year <- "2019"

variance_waterfall_mtd <- read_excel("C:/Users/felpj/Documents/R/R Data/Engineering/MBR Charts/variance_waterfall_mtd.xlsx")
variance_waterfall_ytd <- read_excel("C:/Users/felpj/Documents/R/R Data/Engineering/MBR Charts/variance_waterfall_ytd.xlsx")

variance_waterfall_mtd$desc <- factor(variance_waterfall_mtd$desc,
                                         levels = c("FORECAST",
                                                    "EAST EXP",
                                                    "EAST CHGS",
                                                    "WEST EXP",
                                                    "WEST CHGS",
                                                    "INT'L EXP",
                                                    "INT'L CHGS",
                                                    "OS EXP",
                                                    "OS CHGS",
                                                    "ENG ADMIN EXP",
                                                    "OTHER",
                                                    "ACTUAL"))
variance_waterfall_mtd$id <- seq_along(variance_waterfall_mtd$amount)
variance_waterfall_mtd$type <- ifelse(variance_waterfall_mtd$amount > 0, "fav", "unfav")
variance_waterfall_mtd[variance_waterfall_mtd$desc %in% c("FORECAST", "ACTUAL"), "type"] <- "net"

variance_waterfall_mtd$end <- cumsum(variance_waterfall_mtd$amount) 
variance_waterfall_mtd$end <- c(head(variance_waterfall_mtd$end, -1), 0) ## add zero to last entry in end column
variance_waterfall_mtd$start <- c(0, head(variance_waterfall_mtd$end, -1)) ## zero to the start
variance_waterfall_mtd <- variance_waterfall_mtd[,c(3,1,4,6,5,2)]

variance_waterfall_mtd$type <- as.factor(variance_waterfall_mtd$type)

## ytd charts now

variance_waterfall_ytd$desc <- factor(variance_waterfall_ytd$desc,
                                      levels = c("TARGET",
                                                 "EAST EXP",
                                                 "EAST CHGS",
                                                 "WEST EXP",
                                                 "WEST CHGS",
                                                 "INT'L EXP",
                                                 "INT'L CHGS",
                                                 "OS EXP",
                                                 "OS CHGS",
                                                 "ENG ADMIN EXP",
                                                 "OTHER",
                                                 "ACTUAL"))
variance_waterfall_ytd$id <- seq_along(variance_waterfall_ytd$amount)
variance_waterfall_ytd$type <- ifelse(variance_waterfall_ytd$amount > 0, "fav", "unfav")
variance_waterfall_ytd[variance_waterfall_ytd$desc %in% c("TARGET", "ACTUAL"), "type"] <- "net"

variance_waterfall_ytd$end <- cumsum(variance_waterfall_ytd$amount) 
variance_waterfall_ytd$end <- c(head(variance_waterfall_ytd$end, -1), 0) ## add zero to last entry in end column
variance_waterfall_ytd$start <- c(0, head(variance_waterfall_ytd$end, -1)) ## zero to the start
variance_waterfall_ytd <- variance_waterfall_ytd[,c(3,1,4,6,5,2)]

variance_waterfall_ytd$type <- as.factor(variance_waterfall_ytd$type)
```


```{r Waterfall graph, message=FALSE, warning=FALSE}

strwr <- function(str) gsub(" ", "\n", str)

waterfall_mtd <- ggplot(variance_waterfall_mtd, aes(desc, fill = type)) +
  geom_rect(aes(x = desc, xmin = id - 0.45, xmax = id + 0.45, ymin = end, ymax = start)) +
  scale_fill_manual(values = waterfall_palette) +
  theme(axis.title = element_blank(), 
        legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = bluescope_lightgray),
        plot.title = element_text(hjust = 0.5, size = title_text),
        plot.subtitle = element_text(hjust = 0.5, size = subtitle_text)) +
  scale_x_discrete("", breaks = levels(variance_waterfall_mtd$desc),
                   labels = strwr(levels(variance_waterfall_mtd$desc))) +
  labs(title = paste("Engineering OH Variance", current_month, current_year, sep = " "),
       subtitle = "Forcast to Actual") +
  geom_text(data = subset(variance_waterfall_mtd, type == "fav"), 
            aes(id, end, label = scales::comma(amount)), vjust = 1, size = 3) +
  geom_text(data = subset(variance_waterfall_mtd, type == "unfav"), 
            aes(id, end, label = scales::comma(amount)), vjust = -0.3, size = 3) +
  geom_text(data = subset(variance_waterfall_mtd, type == "net" & id == min(id)), 
            aes(id, end, colour = type, label = scales::comma(end), vjust = ifelse(end < start, 1, -0.3)), size = 3.5) +
  geom_text(data = subset(variance_waterfall_mtd, type == "net" & id == max(id)), 
            aes(id, start, colour = type, label = scales::comma(start), vjust = ifelse(end < start, -0.3, 1)), size = 3.5)

waterfall_ytd <- ggplot(variance_waterfall_ytd, aes(desc, fill = type)) +
  geom_rect(aes(x = desc, xmin = id - 0.45, xmax = id + 0.45, ymin = end, ymax = start)) +
  scale_fill_manual(values = waterfall_palette) +
  theme(axis.title = element_blank(), 
        legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = bluescope_lightgray),
        plot.title = element_text(hjust = 0.5, size = title_text),
        plot.subtitle = element_text(hjust = 0.5, size = subtitle_text)) +
  scale_x_discrete("", breaks = levels(variance_waterfall_ytd$desc),
                   labels = strwr(levels(variance_waterfall_ytd$desc))) +
  labs(title = "Engineering OH Variance FY20",
       subtitle = "Target to Actual") +
  geom_text(data = subset(variance_waterfall_ytd, type == "fav"), 
            aes(id, end, label = scales::comma(amount)), vjust = 1, size = 3) +
  geom_text(data = subset(variance_waterfall_ytd, type == "unfav"), 
            aes(id, end, label = scales::comma(amount)), vjust = -0.3, size = 3) +
  geom_text(data = subset(variance_waterfall_ytd, type == "net" & id == min(id)), 
            aes(id, end, colour = type, label = scales::comma(end), vjust = ifelse(end < start, 1, -0.3)), size = 3.5) +
  geom_text(data = subset(variance_waterfall_ytd, type == "net" & id == max(id)), 
            aes(id, start, colour = type, label = scales::comma(start), vjust = ifelse(end < start, -0.3, 1)), size = 3.5)

print(waterfall_mtd)

ggsave("~/R/R Data/Engineering/MBR Charts/Charts/variance_waterfall_mtd.png", waterfall_mtd, width = 12, height = 3, dpi = 320)

print(waterfall_ytd)

ggsave("~/R/R Data/Engineering/MBR Charts/Charts/variance_waterfall_ytd.png", waterfall_ytd, width = 12, height = 3, dpi = 320)

```


```{r}
grid.newpage()

pushViewport(viewport(layout = grid.layout(nrow = 2, ncol = 1)))

define_region <- function(row, col) {
  viewport(layout.pos.row = row, layout.pos.col = col)
}

print(waterfall_mtd, vp = define_region(row = 1, col = 1))
print(waterfall_ytd, vp = define_region(row = 2, col = 1))

waterfall_one_page <- arrangeGrob(waterfall_mtd, waterfall_ytd, nrow = 2)

ggsave("~/R/R Data/Engineering/waterfall_one_page.png", waterfall_one_page, width = 16, height = 9, dpi = 320)
```

