eng_complexity_lookup <- read_csv("~/R/R Data/S&OP/Engineering/eng_complexity_lookup.csv", 
                                  col_types = cols(`Order Number` = col_character())) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8)) %>%
  select(proj_num,
         Region,
         Complexity)

Engineering_Metrics_Jul19 <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/Engineering Metrics Jul19.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "date", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "skip", "skip"), skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))
Engineering_Metrics_Aug19 <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/Engineering Metrics Aug19.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "date", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "skip", "skip"), skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))
Engineering_Metrics_Sep19 <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/Engineering Metrics Sep19.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "date", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "skip", "skip"), skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))
Engineering_Metrics_Oct19 <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/Engineering Metrics Oct19.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "date", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "skip", "skip"), skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))
Engineering_Metrics_Nov19 <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/Engineering Metrics Nov19.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "date", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "skip", "skip"), skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))
Engineering_Metrics_Dec19 <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/Engineering Metrics Dec19.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "date", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "skip", "skip"), skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))
Engineering_Metrics_Jan20 <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/Engineering Metrics Jan20.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "date", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "skip", "skip"), skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))

Engineering_Metrics_Feb20 <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/Engineering Metrics Feb20.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "date", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "skip", "skip"), skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))

Engineering_Metrics_Mar20 <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/Engineering Metrics Mar20.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "date", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "skip", "skip"), skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))

Engineering_Metrics_Apr20 <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/Engineering Metrics Apr20.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "date", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "skip", "skip"), skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))

fy19_order_summary <- read_excel("~/R/R Data/Engineering/fy21_capacity_planning/order_summary_rpts/fy19_order_summary.xlsx", 
                                 sheet = "fy19_order_summary", col_types = c("text", 
                                                                             "numeric", "text", "text", "text", 
                                                                             "text", "date", "numeric", "numeric", 
                                                                             "text", "text", "text", "text", "text", 
                                                                             "text", "text", "numeric", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "text", "numeric", "numeric", "numeric", 
                                                                             "numeric", "text", "numeric", "numeric", 
                                                                             "numeric", "numeric", "text", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "text", "numeric", "numeric", "numeric", 
                                                                             "numeric", "text", "numeric", "numeric", 
                                                                             "numeric", "numeric", "text", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "text", "numeric", "numeric", "numeric", 
                                                                             "numeric", "text", "numeric", "numeric", 
                                                                             "numeric", "numeric", "text", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "text", "numeric", "numeric", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "text", "numeric", "numeric", "numeric", 
                                                                             "date", "text", "numeric", "numeric", 
                                                                             "numeric", "numeric", "text", "numeric", 
                                                                             "numeric", "numeric", "numeric", 
                                                                             "skip", "skip"),  skip = 41) %>%
  mutate(proj_num = str_sub(`Order Number`, 1,8))


fy20_order_summary <- bind_rows("'JUL-19" = Engineering_Metrics_Jul19,
                                "'AUG-19" = Engineering_Metrics_Aug19,
                                "'SEP-19" = Engineering_Metrics_Sep19,
                                "'OCT-19" = Engineering_Metrics_Oct19,
                                "'NOV-19" = Engineering_Metrics_Nov19,
                                "'DEC-19" = Engineering_Metrics_Dec19,
                                "'JAN-20" = Engineering_Metrics_Jan20,
                                "'FEB-20" = Engineering_Metrics_Feb20,
                                "'MAR-20" = Engineering_Metrics_Mar20,
                                "'APR-20" = Engineering_Metrics_Apr20,
                                .id = "Period")

combined_order_summary <- bind_rows("FY19" = fy19_order_summary,
                                    "FY20" = fy20_order_summary,
                                    .id = "fiscal_year")

combined_order_summary <- combined_order_summary %>%
  mutate(Brand = if_else(str_detect(`Order Type`, "CLAIM"), "CLAIM",
                         if_else(str_detect(`Order Type`, "PART"), "PARTS ORDER",
                                 if_else(str_detect(`Order Type`, "GB"), "BUTLER",
                                         if_else(str_detect(`Order Type`, "VP"), "VP",
                                                 if_else(str_detect(`Order Type`, "CSS/CONV"), "CSS",
                                                         if_else(str_detect(`Order Type`, "CSS/HS"), "HEAVY STRUCTURES",
                                                                 if_else(str_sub(`Order Type`, 1,4) == "ROOF", "ROOF", "Other"))))))),
         eck_month = floor_date(ymd(`ECK Act Comp`), "month"),
         tons = if_else(`Order Status` == "EN", `Planned Tons`, `Eng Mfst Tons`)) %>%
  left_join(eng_complexity_lookup, by = c("proj_num" = "proj_num")) %>%
  clean_names()